### ISSUE TITLE
Open menu and submenu on hover

### ISSUE THREAD

**Issue by sum1190** [kartik-v/yii2-nav-x#13]
Hi, 

As for the title of the issue, is it possible to show menu and sebmenu on hover, instead of open them by click?

Thank you.

**Comment by kartik-v** [comment]
You need to write your own JS for that.

Click behavior for menus is the default bootstrap standard (which is built now mobile first) since HOVER will not work on mobile/tablet devices (that are touch based).

**Comment by sum1190** [comment]
Ok, thank you ;)
