### ISSUE TITLE
Enhancement: Using bootstrap 4

### ISSUE THREAD

**Issue by twinni** [kartik-v/yii2-nav-x#19]
## Steps to reproduce the issue

1. Require  "yiisoft/yii2-bootstrap": "~2.1.0@dev",

## Expected behavior and actual behavior

When I follow those steps, I see the sandwich menu symbol. Menu layout looks weired. Submenu drilldown is not working at all.

Working with bootstrap 3 is fine.

## Environment
Yii 2.0.13-dev
PHP 7.1.7

#### Operating System

- [ ] Windows

#### Libraries

- yii2-nav-x version: 1.2.1

**Comment by kartik-v** [comment]
Currently none of these widgets have been modified to use with bootstrap 4.x.

**Comment by haifahrul** [comment]
Hi Kartik,

Whether there is widget have u made compatible with bootstrap 4.x?

**Comment by kartik-v** [comment]
Not yet... will need time to do this later... it will be a major rewrite for most widgets.

**Comment by kartik-v** [comment]
Update for bootstrap 4 now available.
