### ISSUE TITLE
Class 'kartik\dropdown\DropdownX' not found

### ISSUE THREAD

**Issue by makroxyz** [kartik-v/yii2-nav-x#20]
after upgrade to 1.2.2

**Comment by kartik-v** [comment]
You can update to release v1.2.3.

But you need to install dependency manually as highlighted in README.

Install the dependencies depending on the Bootstrap version used in your app:

1. For Bootstrap 3.x install `kartik-v/yii2-dropdown-x`

```
$ php composer.phar require kartik-v/yii2-dropdown-x "@dev"
```

2. For Bootstrap 4.x install `kartik-v/yii2-bootstrap4-dropdown`

```
$ php composer.phar require kartik-v/yii2-bootstrap4-dropdown "@dev"
```
