### ISSUE TITLE
Exceptions after Updating to 1.2.3

### ISSUE THREAD

**Issue by kasoft** [kartik-v/yii2-nav-x#21]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ?] The issue still exists against the latest `master` branch of yii2-nav-x.
- [ X] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/nav-x).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Update from 1.2.1 to 1.2.3
2.
3.

## Expected behavior and actual behavior
Was working fine before the Update, after update: 
Setting unknown property: kartik\nav\NavXBs3::dropdownOptions
switching back to 1.2.1 and it was working again

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-nav-x version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/nav-x)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-nav-x without other plugins.

**Comment by kartik-v** [comment]
Update to latest release v1.2.4.
